### ISSUE TITLE
Vault chart

### ISSUE THREAD

**Issue by OxMarco** [Ithil-protocol/frontend#87]
and centering of the text inside the cards

**Comment by lsqrl** [comment]
We need to show the interest rate vs. utilization chart: the X axis is the utilization, the Y axis the interest rate.
**Ranges**: X axis from 0 to 100%, Y axis from 0 to max(Y)
**How to compute Y**: the base interest rate is calculated as `Y = [baseFee + X * riskFactor * ( 1 + max(netLoans - insuranceReserve; 0) / netLoans ) ] / 20000` (twenty-thousand in the denominator)
Approximated, when `insuranceReserve` is small, this is simply `(baseFee + X * riskFactor) / 10000`
Notice that this is both token and strategy specific (because of the riskFactor)
